spring:
  application:
    name: kyuhyun

  datasource:
    driver-class-name: org.h2.Driver
    url: 'jdbc:h2:mem:test'   # H2 DB ?? ?? (In-Memory Mode)
    username: root
    password: root

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        show_sql: true
  config:
    import:
     - open_data_portal.yml
     - public_address.yml

## 다운로드 url
download:
  base-url: 'https://www.ftc.go.kr'
  file-url: '/www/downloadBizComm.do?atchFileUrl=dataopen&atchFileNm='
  file-prefix: '통신판매사업자'
  file-subfix: '.csv'

server:
  port: 8081